products:
  bulldozer:
    build:
        main-pkg: .
        os-archs:
          - os: linux
            arch: amd64
          - os: darwin
            arch: amd64
        version-var: github.com/palantir/bulldozer/version.version
    dist:
      dist-type:
        type: bin
group-id: com.palantir.bulldozer
